apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    openshift.io/image.dockerRepositoryCheck: 2017-09-17T14:28:25Z
  creationTimestamp: null
  generation: 2
  labels:
    app: service-per-pod
  name: origin
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: openshift/origin
    from:
      kind: DockerImage
      name: 172.30.1.1:5000/myproject/origin:latest
    generation: 2
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
