apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: service-per-pod
  name: service-per-pod
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: service-per-pod:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: service-per-pod
    git:
      uri: https://github.com/tedsluis/openshift-testing.git
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: origin:latest
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: l2cjfDz3KKlJ9APcuLc4
    type: GitHub
  - generic:
      secret: o7yNZxQRPAT7khO6N3C2
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0
