apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  generation: 1
  labels:
    app: service-per-pod
  name: service-per-pod
spec:
  replicas: 1
  selector:
    app: service-per-pod
    deploymentconfig: service-per-pod
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: service-per-pod
        deploymentconfig: service-per-pod
    spec:
      containers:
      - image: 172.30.1.1:5000/myproject/service-per-pod@sha256:c0b03f812220988487885832735f0dbdcdf57f6734edcf476dcb9653c6d58afa
        imagePullPolicy: Always
        name: service-per-pod
        ports:
        - containerPort: 8443
          protocol: TCP
        - containerPort: 53
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: pod-watch
      serviceAccountName: pod-watch
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - service-per-pod
      from:
        kind: ImageStreamTag
        name: service-per-pod:latest
        namespace: myproject
    type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
